version: '3'

services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back-end
    restart: unless-stopped
    environment:
      - MONGO_HOSTNAME=db
      - HUB_PATH=https://YOUR_JUPYTERHUB_ADDRESS/hub/api
      - USERS_CREATE_KEY=YOUR_KEY
    ports:
      - 3000:3000
    networks:
      - app-network

  db:
    image: mongo:3.6-xenial
    container_name: db
    restart: unless-stopped
    volumes:
      - /data/db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
